#ifndef ASYNCWEBSERVERCONFIG_H
#define ASYNCWEBSERVERCONFIG_H

#ifdef CONFIG_ASYNC_TCP_MAX_ACK_TIME
#undef CONFIG_ASYNC_TCP_MAX_ACK_TIME
#undef CONFIG_ASYNC_TCP_PRIORITY
#undef CONFIG_ASYNC_TCP_STACK_SIZE
#undef CONFIG_ASYNC_TCP_QUEUE_SIZE
#undef CONFIG_ASYNC_TCP_RUNNING_CORE
#undef WS_MAX_QUEUED_MESSAGES
#endif

#define CONFIG_ASYNC_TCP_MAX_ACK_TIME 6000
#define CONFIG_ASYNC_TCP_PRIORITY 0
#define CONFIG_ASYNC_TCP_STACK_SIZE 16384
#define CONFIG_ASYNC_TCP_QUEUE_SIZE 1024
#define CONFIG_ASYNC_TCP_RUNNING_CORE 1
#define WS_MAX_QUEUED_MESSAGES 64

#endif /* ASYNCWEBSERVERCONFIG_H */
