#ifndef ASYNCWEBSERVERCONFIG_H
#define ASYNCWEBSERVERCONFIG_H

#ifdef CONFIG_ASYNC_TCP_MAX_ACK_TIME
#undef CONFIG_ASYNC_TCP_MAX_ACK_TIME
#undef CONFIG_ASYNC_TCP_PRIORITY
#undef CONFIG_ASYNC_TCP_QUEUE_SIZE
#undef CONFIG_ASYNC_TCP_RUNNING_CORE
#undef CONFIG_ASYNC_TCP_STACK_SIZE
#undef WS_MAX_QUEUED_MESSAGES
#endif

#define CONFIG_ASYNC_TCP_MAX_ACK_TIME 3000
#define CONFIG_ASYNC_TCP_PRIORITY 10
#define CONFIG_ASYNC_TCP_QUEUE_SIZE 128
#define CONFIG_ASYNC_TCP_RUNNING_CORE 1
#define CONFIG_ASYNC_TCP_STACK_SIZE 4096
#define WS_MAX_QUEUED_MESSAGES 64

#endif /* ASYNCWEBSERVERCONFIG_H */
